s3:
 account_number: ''
 billing_bucket: ''
 name              : ''
 aws_access_key    : ''
 aws_secret_key    : ''
smtp:
 name             : ''
 user             : ''
 password         : ''
 server           : ''
 sender_address   : 'me@mysite.com'
 port        :    '587'
recipients:
    - address : 'test@test.com'
general:
 format: 'standard'
 filter: ''
 time_zone: 'Europe/London'
 debug: 'true'
cache:
 timeout: '600'
